name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      fail-fast: true

      matrix:
        hostarch: [amd64, arm64, armhf]

    name: Attach ${{ matrix.hostarch }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out code with tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build Debian package
        id: deb
        uses: ebarkie/actions/deb/go@master
        with:
          hostarch: ${{ matrix.hostarch }}
          version: ${{ github.ref }}

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.deb.outputs.asset_path }}
